services:
  logixboard-backend:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    ports:
      - "3001:3001"
    volumes:
      - "./:/usr/app"
    depends_on:
      - logixboard-db
    networks:
      - logixboard_backend
  logixboard-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: logixboard_db
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    ports:
      - "5454:5432"
    networks:
      - logixboard_backend
networks:
  logixboard_backend:
    driver:
      bridge
